### ISSUE TITLE
Improve response

### ISSUE THREAD

**Issue by KimTaehee** [TaeKyuHyeon/discord-relay#7]
1. 에러 발생시 status code 200 대신 400 등 에러 코드 반환
2. response body를 plain text 대신 json으로 반환
partial success에 대해서도 처리 가능해야 함
```
{
  "code": 101200,
  "message": "Post message success",
  "request": 2
  "success": 1
  "failedResult": [
    "channelId": "809052367168733247"
    "reason": "Channel does not exists"
  ]
}
```

에러 code 제안: 
- 101200 (101 모듈의 success)
- 101400 (101 모듈의 400 에러)
- 101500 (101 모듈의 500 에러)

**Comment by tkbro** [comment]
#11 에서 간단한 response 모듈을 추가해서 content type 과 code 에 대한 내용 보강

실패 상황에 대해서 hapi 를 사용하는 만큼 doc 에 나온 boom 도입을 고려해야 할 듯.
